export default {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 4,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Long Shirt",
      category: "Shirts",
      image: "/images/d2.jpg",
      price: 20,
      brand: "Winston",
      rating: 4.2,
      numReviews: 5,
      countInStock: 6,
    },
    {
      _id: "3",
      name: "Short Pants",
      category: "Pants",
      image: "/images/d3.jpg",
      price: 40,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 6,
      countInStock: 6,
    },
    {
      _id: "4",
      name: "Brown Shirt",
      category: "Shirts",
      image: "/images/d4.jpg",
      price: 60,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 7,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "Black Pants",
      category: "Pants",
      image: "/images/d5.jpg",
      price: 80,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 8,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "Long Pants",
      category: "Pants",
      image: "/images/d6.jpg",
      price: 100,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 30,
      countInStock: 6,
    },
  ],
};
