export default {
  products: [
    {
      _id: "1",
      name: "Slim Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 4,
    },
    {
      _id: "2",
      name: "Long Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 50,
      brand: "Winston",
      rating: 4.2,
      numReviews: 5,
    },
    {
      _id: "3",
      name: "Short Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 70,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 6,
    },
    {
      _id: "4",
      name: "Brown Shirt",
      category: "Shirts",
      image: "/images/d1.jpg",
      price: 70,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 7,
    },
    {
      _id: "5",
      name: "Just Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 70,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 8,
    },
    {
      _id: "6",
      name: "Long Pants",
      category: "Pants",
      image: "/images/d1.jpg",
      price: 70,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
    },
  ],
};
